# Generated by Django 5.2.5 on 2025-09-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='addres',
            new_name='address',
        ),
    ]
