# Generated by Django 5.2 on 2025-07-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_company_product_delete_account_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Course',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='posts.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
